# Generated by Django 5.2.16 on 2026-08-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='centre',
            field=models.CharField(choices=[('MUMBAI', 'Mumbai'), ('HYDERABAD', 'Hyderabad'), ('ONLINE', 'Online'), ('ALL', 'All Centres')], default='ALL', max_length=15),
        ),
    ]
