# Generated by Django 5.2.16 on 2026-09-04 17:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('courses', '0002_centrecontact'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('audience', models.CharField(choices=[('ALL_JOINED', 'All Joined Students'), ('MUMBAI', 'Mumbai Students'), ('HYDERABAD', 'Hyderabad Students'), ('ONLINE', 'Online Students')], default='ALL_JOINED', max_length=20)),
                ('sent_count', models.IntegerField(default=0)),
                ('failed_count', models.IntegerField(default=0)),
                ('sent_at', models.DateTimeField(auto_now_add=True)),
                ('sent_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='broadcasts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Broadcast',
                'verbose_name_plural': 'Broadcasts',
                'ordering': ['-sent_at'],
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, choices=[('MALE', 'Male'), ('FEMALE', 'Female'), ('OTHER', 'Other')], max_length=10)),
                ('address', models.TextField(blank=True)),
                ('education', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ENQUIRED', 'Enquired'), ('JOINED', 'Joined'), ('DROPPED', 'Dropped Out')], default='ENQUIRED', max_length=15)),
                ('centre', models.CharField(choices=[('MUMBAI', 'Mumbai'), ('HYDERABAD', 'Hyderabad'), ('ONLINE', 'Online'), ('NOT_DECIDED', 'Not Decided')], default='NOT_DECIDED', max_length=20)),
                ('referred_by', models.CharField(choices=[('REFERRAL', 'Referral'), ('WALK_IN', 'Walk-in'), ('SOCIAL_MEDIA', 'Social Media'), ('OTHER', 'Other')], default='WALK_IN', max_length=20)),
                ('enquiry_date', models.DateField(blank=True, null=True)),
                ('joined_date', models.DateField(blank=True, null=True)),
                ('total_fee', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('remarks', models.TextField(blank=True)),
                ('last_birthday_wish_year', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='added_students', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='students', to='courses.course')),
            ],
            options={
                'verbose_name': 'Student',
                'verbose_name_plural': 'Students',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reminder_type', models.CharField(choices=[('FEE_REMINDER', 'Fee Reminder'), ('FOLLOW_UP', 'Follow-up Enquiry'), ('CUSTOM', 'Custom Reminder')], default='CUSTOM', max_length=20)),
                ('message', models.TextField()),
                ('remind_at', models.DateTimeField()),
                ('repeat_interval', models.CharField(choices=[('NONE', 'No Repeat'), ('WEEKLY', 'Every Week'), ('MONTHLY', 'Every Month')], default='NONE', max_length=10)),
                ('is_sent', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='students.student')),
            ],
            options={
                'verbose_name': 'Reminder',
                'verbose_name_plural': 'Reminders',
                'ordering': ['remind_at'],
            },
        ),
        migrations.CreateModel(
            name='FeePayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('payment_mode', models.CharField(choices=[('CASH', 'Cash'), ('UPI', 'UPI'), ('BANK_TRANSFER', 'Bank Transfer'), ('CHEQUE', 'Cheque'), ('OTHER', 'Other')], default='CASH', max_length=20)),
                ('receipt_note', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_payments', to=settings.AUTH_USER_MODEL)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fee_payments', to='students.student')),
            ],
            options={
                'verbose_name': 'Fee Payment',
                'verbose_name_plural': 'Fee Payments',
                'ordering': ['-payment_date'],
            },
        ),
    ]
