# Generated by Django 5.2.16 on 2026-08-15 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admissions', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='admission',
            name='preferred_centre',
            field=models.CharField(choices=[('MUMBAI', 'Mumbai'), ('HYDERABAD', 'Hyderabad'), ('ONLINE', 'Online'), ('NOT_DECIDED', 'Not Decided')], default='NOT_DECIDED', max_length=20),
        ),
    ]
