# Generated by Django 5.2.16 on 2026-08-15 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='message',
        ),
        migrations.AddField(
            model_name='enquiry',
            name='education',
            field=models.CharField(blank=True, help_text='Highest qualification', max_length=200),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='enquiry_date',
            field=models.DateField(blank=True, help_text='Date of walk-in or enquiry', null=True),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='fees_type',
            field=models.CharField(blank=True, choices=[('CRASH_COURSE', 'Crash Course'), ('DIPLOMA', 'Diploma'), ('BSC', 'B.Sc'), ('OTHER', 'Other')], max_length=20),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='location',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='payment_made',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='enquiry',
            name='referred_by',
            field=models.CharField(choices=[('REFERRAL', 'Referral'), ('JD', 'JD'), ('WALK_IN', 'Walk-in'), ('SOCIAL_MEDIA', 'Social Media'), ('LINKEDIN', 'LinkedIn'), ('OTHER', 'Other')], default='WALK_IN', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='status',
            field=models.CharField(choices=[('NEW', 'New'), ('FOLLOW_UP', 'Follow Up Required'), ('ENROLLED', 'Enrolled'), ('REJECTED', 'Rejected')], default='NEW', max_length=15),
        ),
    ]
