# Generated by Django 5.2.16 on 2026-08-15 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0002_remove_enquiry_message_enquiry_education_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='enquiry',
            name='preferred_centre',
            field=models.CharField(choices=[('MUMBAI', 'Mumbai'), ('HYDERABAD', 'Hyderabad'), ('ONLINE', 'Online'), ('NOT_DECIDED', 'Not Decided')], default='NOT_DECIDED', help_text='Which VKS centre does the student want to join?', max_length=20),
        ),
        migrations.AlterField(
            model_name='enquiry',
            name='location',
            field=models.CharField(blank=True, help_text='Where the student lives', max_length=200),
        ),
    ]
