# Generated by Django 5.2.16 on 2026-08-15 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('enquiries', '0003_enquiry_preferred_centre_alter_enquiry_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enquiry',
            name='payment_made',
        ),
    ]
