# Generated by Django 5.2.16 on 2026-08-15 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CentreContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('centre', models.CharField(choices=[('MUMBAI', 'Mumbai'), ('HYDERABAD', 'Hyderabad'), ('ONLINE', 'Online')], max_length=20, unique=True)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('address', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Centre Contact Details',
                'verbose_name_plural': 'Centre Contact Details',
            },
        ),
    ]
